### ISSUE TITLE
mask value in crf

### ISSUE THREAD

**Issue by avinashsai** [howardhsu/Double-Embeddings-and-CNN-based-Sequence-Labeling-for-Aspect-Extraction#11]
Hi,
Thanks for the code.
I wanted to what is the x_mask and how is it calculated when passed to crf ??

**Comment by howardhsu** [comment]
It's a boolean matrix with non <pad> tokens a value of True and <pad> with a value of False, which is computed as:
X[offset:offset+batch_size]!=0
