### ISSUE TITLE
CRF开关问题

### ISSUE THREAD

**Issue by WadeYin9712** [howardhsu/Double-Embeddings-and-CNN-based-Sequence-Labeling-for-Aspect-Extraction#3]
您好，感谢开源！我试了你程序中的CRF，但是CRF的loss值非常大，请问您程序中的crf层是怎么使用的呢？谢谢

**Comment by howardhsu** [comment]
感谢您对我code的关注。

CRF计算的是score （具体参考allenNLP），不是CE loss，数值上跟CE不在一个数量级。

我的Github 上的 CRF 没时间做很好的整理，不确定是否后处理的code是否完整。

**Comment by WadeYin9712** [comment]
好的谢谢您！辛苦！
